export const greetings = [
    "Hello! 👋",
    "Hi there! 😊",
    "Hey! What's up?",
    "Greetings, traveler! 🌍",
    "Namaste 🙏",
    "Hola! 🇪🇸",
    "Bonjour! 🇫🇷",
    "Ciao! 🇮🇹",
    "Konnichiwa! 🇯🇵",
    "Annyeonghaseyo! 🇰🇷",
    "Salaam! 🕌",
    "Shalom! ✡️",
    "Hallo! 🇩🇪",
    "Hej! 🇸🇪",
    "Olá! 🇵🇹",
    "Zdravstvuyte! 🇷🇺",
    "Sawubona! 🇿🇦",
    "Nǐ hǎo! 🇨🇳",
    "As-salamu alaykum 🤝",
    "Vanakkam! 🇮🇳",
];